project_id = "qozthicyahnfsewsehys"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://lovable.dev"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[edge_runtime]
enabled = true
port = 54288

[functions.send-digital-product]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.process-payment-splits]
verify_jwt = false

[functions.create-paystack-subaccount]
verify_jwt = false