// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qozthicyahnfsewsehys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvenRoaWN5YWhuZnNld3NlaHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzQ2MDksImV4cCI6MjA3MDY1MDYwOX0.oHDiAIJeun2YsyIRY15D1N7sKR5S70Jxd8UwvuNLdVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});